//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories
    {
        public int ct_id { get; set; }
        public string ct_name { get; set; }
        public int ct_sort_seq { get; set; }
        public int ct_default { get; set; }
    }
}
