//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class code_review_project_settings
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> tracker_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<bool> hide_code_review_tab { get; set; }
        public Nullable<int> auto_relation { get; set; }
        public Nullable<int> assignment_tracker_id { get; set; }
        public string auto_assign { get; set; }
        public int lock_version { get; set; }
        public Nullable<bool> tracker_in_review_dialog { get; set; }
    }
}
