//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class code_reviews
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> change_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> line { get; set; }
        public Nullable<int> updated_by_id { get; set; }
        public int lock_version { get; set; }
        public Nullable<int> status_changed_from { get; set; }
        public Nullable<int> status_changed_to { get; set; }
        public Nullable<int> issue_id { get; set; }
        public string action_type { get; set; }
        public string file_path { get; set; }
        public string rev { get; set; }
        public string rev_to { get; set; }
        public Nullable<int> attachment_id { get; set; }
        public int file_count { get; set; }
    }
}
