//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashboard_items
    {
        public int ds_id { get; set; }
        public int ds_user { get; set; }
        public int ds_report { get; set; }
        public string ds_chart_type { get; set; }
        public int ds_col { get; set; }
        public int ds_row { get; set; }
    }
}
