//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class git_commits
    {
        public int gitcom_id { get; set; }
        public string gitcom_commit { get; set; }
        public int gitcom_bug { get; set; }
        public string gitcom_repository { get; set; }
        public string gitcom_author { get; set; }
        public string gitcom_git_date { get; set; }
        public System.DateTime gitcom_btnet_date { get; set; }
        public string gitcom_msg { get; set; }
    }
}
