//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class kb_articles
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string content { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int author_id { get; set; }
        public Nullable<int> comments_count { get; set; }
        public Nullable<int> project_id { get; set; }
        public int updater_id { get; set; }
    }
}
