//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class priorities
    {
        public int pr_id { get; set; }
        public string pr_name { get; set; }
        public int pr_sort_seq { get; set; }
        public string pr_background_color { get; set; }
        public string pr_style { get; set; }
        public int pr_default { get; set; }
    }
}
