//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_user_xref
    {
        public int pu_id { get; set; }
        public int pu_project { get; set; }
        public int pu_user { get; set; }
        public int pu_auto_subscribe { get; set; }
        public int pu_permission_level { get; set; }
        public int pu_admin { get; set; }
    }
}
