//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerToRedmineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class reports
    {
        public int rp_id { get; set; }
        public string rp_desc { get; set; }
        public string rp_sql { get; set; }
        public string rp_chart_type { get; set; }
    }
}
