//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class chart_time_entries
    {
        public int id { get; set; }
        public int day { get; set; }
        public int week { get; set; }
        public int month { get; set; }
        public float logged_hours { get; set; }
        public int entries { get; set; }
        public int user_id { get; set; }
        public Nullable<int> issue_id { get; set; }
        public Nullable<int> activity_id { get; set; }
        public int project_id { get; set; }
    }
}
