//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class chart_issue_statuses
    {
        public int id { get; set; }
        public int day { get; set; }
        public int week { get; set; }
        public int month { get; set; }
        public int project_id { get; set; }
        public int issue_id { get; set; }
        public int status_id { get; set; }
    }
}
