//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class chart_saved_conditions
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> project_id { get; set; }
        public string conditions { get; set; }
        public string chart { get; set; }
    }
}
