//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class code_review_assignments
    {
        public int id { get; set; }
        public Nullable<int> issue_id { get; set; }
        public Nullable<int> change_id { get; set; }
        public Nullable<int> attachment_id { get; set; }
        public string file_path { get; set; }
        public string rev { get; set; }
        public string rev_to { get; set; }
        public string action_type { get; set; }
        public Nullable<int> changeset_id { get; set; }
    }
}
