//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_fields_projects
    {
        public int custom_field_id { get; set; }
        public int project_id { get; set; }
    }
}
