//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_roles
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public int role_id { get; set; }
        public Nullable<int> inherited_from { get; set; }
    }
}
