//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class redmineEntities : DbContext
    {
        public redmineEntities()
            : base("name=redmineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<attachments> attachments { get; set; }
        public DbSet<auth_sources> auth_sources { get; set; }
        public DbSet<boards> boards { get; set; }
        public DbSet<changes> changes { get; set; }
        public DbSet<changeset_parents> changeset_parents { get; set; }
        public DbSet<changesets> changesets { get; set; }
        public DbSet<changesets_issues> changesets_issues { get; set; }
        public DbSet<chart_done_ratios> chart_done_ratios { get; set; }
        public DbSet<chart_issue_statuses> chart_issue_statuses { get; set; }
        public DbSet<chart_saved_conditions> chart_saved_conditions { get; set; }
        public DbSet<chart_time_entries> chart_time_entries { get; set; }
        public DbSet<chats> chats { get; set; }
        public DbSet<code_review_assignments> code_review_assignments { get; set; }
        public DbSet<code_review_project_settings> code_review_project_settings { get; set; }
        public DbSet<code_review_user_settings> code_review_user_settings { get; set; }
        public DbSet<code_reviews> code_reviews { get; set; }
        public DbSet<comments> comments { get; set; }
        public DbSet<custom_fields> custom_fields { get; set; }
        public DbSet<custom_fields_projects> custom_fields_projects { get; set; }
        public DbSet<custom_fields_trackers> custom_fields_trackers { get; set; }
        public DbSet<custom_values> custom_values { get; set; }
        public DbSet<documents> documents { get; set; }
        public DbSet<enabled_modules> enabled_modules { get; set; }
        public DbSet<enumerations> enumerations { get; set; }
        public DbSet<groups_users> groups_users { get; set; }
        public DbSet<issue_categories> issue_categories { get; set; }
        public DbSet<issue_relations> issue_relations { get; set; }
        public DbSet<issue_statuses> issue_statuses { get; set; }
        public DbSet<issues> issues { get; set; }
        public DbSet<journal_details> journal_details { get; set; }
        public DbSet<journals> journals { get; set; }
        public DbSet<kb_articles> kb_articles { get; set; }
        public DbSet<kb_categories> kb_categories { get; set; }
        public DbSet<member_roles> member_roles { get; set; }
        public DbSet<members> members { get; set; }
        public DbSet<messages> messages { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<open_id_authentication_associations> open_id_authentication_associations { get; set; }
        public DbSet<open_id_authentication_nonces> open_id_authentication_nonces { get; set; }
        public DbSet<projects> projects { get; set; }
        public DbSet<projects_trackers> projects_trackers { get; set; }
        public DbSet<queries> queries { get; set; }
        public DbSet<ratings> ratings { get; set; }
        public DbSet<repositories> repositories { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<schema_migrations> schema_migrations { get; set; }
        public DbSet<settings> settings { get; set; }
        public DbSet<taggings> taggings { get; set; }
        public DbSet<tags> tags { get; set; }
        public DbSet<time_entries> time_entries { get; set; }
        public DbSet<tokens> tokens { get; set; }
        public DbSet<trackers> trackers { get; set; }
        public DbSet<user_preferences> user_preferences { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<versions> versions { get; set; }
        public DbSet<viewings> viewings { get; set; }
        public DbSet<watchers> watchers { get; set; }
        public DbSet<wiki_content_versions> wiki_content_versions { get; set; }
        public DbSet<wiki_contents> wiki_contents { get; set; }
        public DbSet<wiki_pages> wiki_pages { get; set; }
        public DbSet<wiki_redirects> wiki_redirects { get; set; }
        public DbSet<wikis> wikis { get; set; }
        public DbSet<workflows> workflows { get; set; }
    }
}
