//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class taggings
    {
        public int id { get; set; }
        public Nullable<int> tag_id { get; set; }
        public Nullable<int> taggable_id { get; set; }
        public string taggable_type { get; set; }
        public Nullable<int> tagger_id { get; set; }
        public string tagger_type { get; set; }
        public string context { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
