//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug_user
    {
        public int bu_bug { get; set; }
        public int bu_user { get; set; }
        public int bu_flag { get; set; }
        public Nullable<System.DateTime> bu_flag_datetime { get; set; }
        public int bu_seen { get; set; }
        public Nullable<System.DateTime> bu_seen_datetime { get; set; }
        public int bu_vote { get; set; }
        public Nullable<System.DateTime> bu_vote_datetime { get; set; }
    }
}
