//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug_relationships
    {
        public int re_id { get; set; }
        public int re_bug1 { get; set; }
        public int re_bug2 { get; set; }
        public string re_type { get; set; }
        public int re_direction { get; set; }
    }
}
