//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BugTrackerEntities : DbContext
    {
        public BugTrackerEntities()
            : base("name=BugTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bug_post_attachments> bug_post_attachments { get; set; }
        public DbSet<bug_posts> bug_posts { get; set; }
        public DbSet<bug_relationships> bug_relationships { get; set; }
        public DbSet<bug_subscriptions> bug_subscriptions { get; set; }
        public DbSet<bug_tasks> bug_tasks { get; set; }
        public DbSet<bug_user> bug_user { get; set; }
        public DbSet<bugs> bugs { get; set; }
        public DbSet<categories> categories { get; set; }
        public DbSet<custom_col_metadata> custom_col_metadata { get; set; }
        public DbSet<dashboard_items> dashboard_items { get; set; }
        public DbSet<emailed_links> emailed_links { get; set; }
        public DbSet<git_affected_paths> git_affected_paths { get; set; }
        public DbSet<git_commits> git_commits { get; set; }
        public DbSet<hg_affected_paths> hg_affected_paths { get; set; }
        public DbSet<hg_revisions> hg_revisions { get; set; }
        public DbSet<orgs> orgs { get; set; }
        public DbSet<priorities> priorities { get; set; }
        public DbSet<project_user_xref> project_user_xref { get; set; }
        public DbSet<projects> projects { get; set; }
        public DbSet<queries> queries { get; set; }
        public DbSet<queued_notifications> queued_notifications { get; set; }
        public DbSet<reports> reports { get; set; }
        public DbSet<sessions> sessions { get; set; }
        public DbSet<statuses> statuses { get; set; }
        public DbSet<svn_affected_paths> svn_affected_paths { get; set; }
        public DbSet<svn_revisions> svn_revisions { get; set; }
        public DbSet<user_defined_attribute> user_defined_attribute { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<votes_view> votes_view { get; set; }
    }
}
