//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_col_metadata
    {
        public int ccm_colorder { get; set; }
        public string ccm_dropdown_vals { get; set; }
        public Nullable<int> ccm_sort_seq { get; set; }
        public string ccm_dropdown_type { get; set; }
    }
}
