//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class git_affected_paths
    {
        public int gitap_id { get; set; }
        public int gitap_gitcom_id { get; set; }
        public string gitap_action { get; set; }
        public string gitap_path { get; set; }
    }
}
