//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class hg_affected_paths
    {
        public int hgap_id { get; set; }
        public int hgap_hgrev_id { get; set; }
        public string hgap_action { get; set; }
        public string hgap_path { get; set; }
    }
}
