//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class queries
    {
        public int qu_id { get; set; }
        public string qu_desc { get; set; }
        public string qu_sql { get; set; }
        public Nullable<int> qu_default { get; set; }
        public Nullable<int> qu_user { get; set; }
        public Nullable<int> qu_org { get; set; }
    }
}
