//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class statuses
    {
        public int st_id { get; set; }
        public string st_name { get; set; }
        public int st_sort_seq { get; set; }
        public string st_style { get; set; }
        public int st_default { get; set; }
    }
}
