//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class svn_revisions
    {
        public int svnrev_id { get; set; }
        public int svnrev_revision { get; set; }
        public int svnrev_bug { get; set; }
        public string svnrev_repository { get; set; }
        public string svnrev_author { get; set; }
        public string svnrev_svn_date { get; set; }
        public System.DateTime svnrev_btnet_date { get; set; }
        public string svnrev_msg { get; set; }
    }
}
